// ÉLAN locaties voor de Find-us globe + Nederland-kaart.
// Adrestekst = bron (Elan verkoop overzicht).
// Coördinaten: OpenStreetMap winkel-POI waar beschikbaar, anders PDOK/BAG (adres-niveau).
// Benodigd: name, country, city, lat, lng. type: 'hq' | 'store' | 'distributor'.

export const locations = [
  {
    id: 'nl-hq',
    name: 'ÉLAN World HQ',
    country: 'Netherlands',
    city: 'Capelle aan den IJssel',
    address: 'Cypresbaan 55, 2908 LT',
    lat: 51.9292,
    lng: 4.5772,
    type: 'hq',
  },
  {
    id: 'nl-kct',
    name: 'KCT',
    country: 'Netherlands',
    city: 'Rotterdam',
    address: '1e Middelandsstraat, 3014 BC',
    lat: 51.919332,
    lng: 4.464067,
    type: 'store',
  },
  {
    id: 'nl-warung-sayang',
    name: 'Warung Sayang',
    country: 'Netherlands',
    city: 'Rotterdam',
    address: 'Pretorialaan 14a, 3072 EM',
    lat: 51.901442,
    lng: 4.497644,
    type: 'store',
  },
  {
    id: 'nl-super-gym',
    name: 'Super Gym',
    country: 'Netherlands',
    city: 'Rijswijk',
    address: 'Van Gijnstraat 16, 2288 GB',
    lat: 52.037695,
    lng: 4.329846,
    type: 'store',
  },
  {
    id: 'nl-black-diamond-kitchen',
    name: 'Black Diamond Kitchen',
    country: 'Netherlands',
    city: 'Rotterdam',
    address: 'Straatweg 51a, 3051 BC',
    lat: 51.944717,
    lng: 4.482439,
    type: 'store',
  },
  {
    id: 'nl-alexandria',
    name: 'alexandria',
    country: 'Netherlands',
    city: 'Rotterdam',
    address: 'Leningradweg 50, 3066 SH',
    lat: 51.938048,
    lng: 4.56003,
    type: 'store',
  },
  {
    id: 'nl-radjoe-art',
    name: 'Radjoe Art',
    country: 'Netherlands',
    city: 'Rotterdam',
    address: 'Hoogstraat 4a, 3011 PN',
    lat: 51.923411,
    lng: 4.495636,
    type: 'store',
  },
  {
    id: 'nl-abi-supermarkt',
    name: 'Abi Supermarkt',
    country: 'Netherlands',
    city: 'Rotterdam',
    address: 'Samuel Esmeijerplein 5, 3067 AN',
    lat: 51.940872,
    lng: 4.548989,
    type: 'store',
  },
  {
    id: 'nl-minimarkte-chaipi',
    name: 'Minimarkte Chaipi',
    country: 'Netherlands',
    city: 'Gouda',
    address: 'Oosthaven 35, 2801 PD',
    lat: 52.008917,
    lng: 4.712396,
    type: 'store',
  },
  {
    id: 'nl-tabakshop-spuiweg',
    name: 'Tabakshop Spuiweg',
    country: 'Netherlands',
    city: 'Dordrecht',
    address: 'Spuiweg 2, 3311 GV',
    lat: 51.811468,
    lng: 4.663518,
    type: 'store',
  },
  {
    id: 'nl-sportcentrum-brothers',
    name: 'Sportcentrum Brothers',
    country: 'Netherlands',
    city: 'Nieuwerkerk aan den IJssel',
    address: '1e Tochteweg 13a, 2913 LN',
    lat: 51.981873,
    lng: 4.613406,
    type: 'store',
  },
  {
    id: 'nl-midnight-roti-shop-ypenburg',
    name: 'Midnight Roti Shop Ypenburg',
    country: 'Netherlands',
    city: '\'s-Gravenhage',
    address: 'Vuursteen 5, 2497 CZ',
    lat: 52.040404,
    lng: 4.368475,
    type: 'store',
  },
  {
    id: 'nl-midnight-roti-shop-torenstra',
    name: 'Midnight Roti shop Torenstraat',
    country: 'Netherlands',
    city: '\'s-Gravenhage',
    address: 'Torenstraat 18, 2513 BS',
    lat: 52.077064,
    lng: 4.306208,
    type: 'store',
  },
  {
    id: 'nl-midnight-roti-shop-escamplaa',
    name: 'Midnight Roti shop Escamplaan',
    country: 'Netherlands',
    city: '\'s-Gravenhage',
    address: 'Escamplaan 1, 2547 GA',
    lat: 52.065455,
    lng: 4.278609,
    type: 'store',
  },
  {
    id: 'nl-avondwinkel-twinny',
    name: 'Avondwinkel Twinny',
    country: 'Netherlands',
    city: '\'s-Gravenhage',
    address: 'Aert van der Goesstraat 10, 2582 AK',
    lat: 52.088354,
    lng: 4.27677,
    type: 'store',
  },
  {
    id: 'nl-supermarkt-franselaan',
    name: 'Supermarkt Franselaan',
    country: 'Netherlands',
    city: 'Rotterdam',
    address: 'Franselaan 285a, 3028 AD',
    lat: 51.917658,
    lng: 4.417979,
    type: 'store',
  },
  {
    id: 'nl-night-2-night',
    name: 'Night 2 Night',
    country: 'Netherlands',
    city: '\'s-Gravenhage',
    address: 'Herengracht 1, 2511 EG',
    lat: 52.080329,
    lng: 4.318508,
    type: 'store',
  },
  {
    id: 'nl-slijterij-yonas',
    name: 'Slijterij Yonas',
    country: 'Netherlands',
    city: 'Rotterdam',
    address: 'Crooswijkseweg 89b, 3034 HG',
    lat: 51.931275,
    lng: 4.49282,
    type: 'store',
  },
  {
    id: 'nl-plus-viergever',
    name: 'Plus Viergever',
    country: 'Netherlands',
    city: 'Rotterdam',
    address: 'Schere 4 6, 3085 DW',
    lat: 51.874824,
    lng: 4.489253,
    type: 'store',
  },
  {
    id: 'nl-toko-dingo',
    name: 'Toko Dingo',
    country: 'Netherlands',
    city: 'Dordrecht',
    address: 'Spuiweg 62, 3311 GV',
    lat: 51.810718,
    lng: 4.66329,
    type: 'store',
  },
  {
    id: 'nl-supermarkt-en-slijterij-krui',
    name: 'Supermarkt en Slijterij Kruiskade',
    country: 'Netherlands',
    city: 'Rotterdam',
    address: 'West-Kruiskade 15a, 3014 AJ',
    lat: 51.920764,
    lng: 4.469942,
    type: 'store',
  },
  {
    id: 'nl-house-of-surinam',
    name: 'House Of Surinam',
    country: 'Netherlands',
    city: 'Rotterdam',
    address: '22 Hogenbanweg 105a, 3042 AX',
    lat: 51.93682,
    lng: 4.428124,
    type: 'store',
  },
  {
    id: 'nl-vreugdenhil',
    name: 'Vreugdenhil',
    country: 'Netherlands',
    city: 'Rotterdam',
    address: 'Lusthofstraat 62b, 3061 WG',
    lat: 51.923756,
    lng: 4.510841,
    type: 'store',
  },
  {
    id: 'nl-new-tropische-shop',
    name: 'New Tropische Shop',
    country: 'Netherlands',
    city: 'Rotterdam',
    address: 'Schiedamseweg 87, 3026 AD',
    lat: 51.910315,
    lng: 4.444481,
    type: 'store',
  },
  {
    id: 'nl-active-gym',
    name: 'Active Gym',
    country: 'Netherlands',
    city: 'Capelle aan den IJssel',
    address: 'Fascinatio Boulevard 1140, 2909 VA',
    lat: 51.918908,
    lng: 4.546857,
    type: 'store',
  },
  {
    id: 'nl-lezzer-zuivelproducten',
    name: 'Lezzer Zuivelproducten',
    country: 'Netherlands',
    city: 'Rotterdam',
    address: 'Singaporestraat 69, 3047 BE',
    lat: 51.943276,
    lng: 4.401149,
    type: 'store',
  },
  {
    id: 'nl-surinaamse-verleiding',
    name: 'Surinaamse Verleiding',
    country: 'Netherlands',
    city: 'Stolwijk',
    address: 'Dorpsplein 4, 2821 AR',
    lat: 51.972035,
    lng: 4.771465,
    type: 'store',
  },
  {
    id: 'nl-coasa-django',
    name: 'Coasa Django',
    country: 'Netherlands',
    city: 'Dordrecht',
    address: 'Spuiweg 62, 3311 GV',
    lat: 51.810718,
    lng: 4.66329,
    type: 'store',
  },
  {
    id: 'nl-avondwinkel-overschie',
    name: 'avondwinkel Overschie',
    country: 'Netherlands',
    city: 'Rotterdam',
    address: 'Burg. Baumannlaan 26, 3043 AR',
    lat: 51.939922,
    lng: 4.423772,
    type: 'store',
  },
  {
    id: 'nl-nightshop-capelle',
    name: 'Nightshop Capelle',
    country: 'Netherlands',
    city: 'Capelle aan den IJssel',
    address: 'Kanaalweg 23a, 2903 LR',
    lat: 51.935605,
    lng: 4.581481,
    type: 'store',
  },
  {
    id: 'nl-nieuwe-haven-markt',
    name: 'Nieuwe Haven Markt',
    country: 'Netherlands',
    city: 'Schiedam',
    address: 'Nieuwe Haven 275b, 3117 AC',
    lat: 51.916378,
    lng: 4.393129,
    type: 'store',
  },
  {
    id: 'nl-tabakzone',
    name: 'Tabakzone',
    country: 'Netherlands',
    city: 'Rotterdam',
    address: 'Ceintuurbaan 100, 3051 KD',
    lat: 51.942291,
    lng: 4.480307,
    type: 'store',
  },
  {
    id: 'nl-avondwinkel-donna',
    name: 'Avondwinkel Donna',
    country: 'Netherlands',
    city: '\'s-Gravenhage',
    address: 'Loosduinsekade 413, 2571 CH',
    lat: 52.067781,
    lng: 4.274471,
    type: 'store',
  },
  {
    id: 'nl-acs',
    name: 'ACS',
    country: 'Netherlands',
    city: 'Rotterdam',
    address: 'Vareseweg 1, 3047 AT',
    lat: 51.947093,
    lng: 4.412558,
    type: 'store',
  },
  {
    id: 'nl-superfood',
    name: 'Superfood',
    country: 'Netherlands',
    city: 'Schiedam',
    address: 'Algerastraat 19, 3125 BS',
    lat: 51.93433,
    lng: 4.403051,
    type: 'store',
  },
  {
    id: 'nl-bgs-nutrition',
    name: 'BGS Nutrition',
    country: 'Netherlands',
    city: 'Rotterdam',
    address: 'Metaalhof 50, 3067 GM',
    lat: 51.949095,
    lng: 4.543873,
    type: 'store',
  },
  {
    id: 'nl-koas-foods',
    name: 'Koas Foods',
    country: 'Netherlands',
    city: 'Bleiswijk',
    address: 'Christiaan Huygensstraat 11, 2665 KX',
    lat: 52.013093,
    lng: 4.5406,
    type: 'store',
  },
  {
    id: 'nl-powerleague-rotterdam',
    name: 'Powerleague Rotterdam',
    country: 'Netherlands',
    city: 'Rotterdam',
    address: 'Leningradplaats 12, 3066 SG',
    lat: 51.939322,
    lng: 4.558735,
    type: 'store',
  },
  {
    id: 'nl-far-west',
    name: 'Far West',
    country: 'Netherlands',
    city: '\'s-Gravenhage',
    address: 'Vlist 2, 2491 CB',
    lat: 52.066671,
    lng: 4.3887,
    type: 'store',
  },
  {
    id: 'nl-stationswinkel-nieuwland',
    name: 'Stationswinkel Nieuwland',
    country: 'Netherlands',
    city: 'Schiedam',
    address: 'Nieuwlandplein 39, 3118 AE',
    lat: 51.920602,
    lng: 4.385194,
    type: 'store',
  },
  {
    id: 'nl-msp',
    name: 'MSP',
    country: 'Netherlands',
    city: '\'s-Gravenhage',
    address: 'Westvlietweg 64b, 2495 AA',
    lat: 52.064006,
    lng: 4.364279,
    type: 'store',
  },
  {
    id: 'nl-7days-polski-sklep',
    name: '7days polski sklep',
    country: 'Netherlands',
    city: 'Boskoop',
    address: 'Burgermester Colijnstraat 22f, 2771 GD',
    lat: 52.075189,
    lng: 4.659088,
    type: 'store',
  },
  {
    id: 'nl-de-dijk-avondmarkt',
    name: 'De Dijk Avondmarkt',
    country: 'Netherlands',
    city: 'Rotterdam',
    address: 'Willem Ruyslaan 24a, 3063 ES',
    lat: 51.92112,
    lng: 4.506159,
    type: 'store',
  },
  {
    id: 'nl-bollywood',
    name: 'Bollywood',
    country: 'Netherlands',
    city: '\'s-Gravenhage',
    address: 'Spui 6, 2511 BS',
    lat: 52.078322,
    lng: 4.314173,
    type: 'store',
  },
  {
    id: 'nl-slijterij-almelo',
    name: 'Slijterij Almelo',
    country: 'Netherlands',
    city: '\'s-Gravenhage',
    address: 'Almeloplein 64, 2533 AD',
    lat: 52.055002,
    lng: 4.27478,
    type: 'store',
  },
  {
    id: 'nl-knight-mart',
    name: 'Knight-Mart',
    country: 'Netherlands',
    city: 'Zoetermeer',
    address: 'Oranjelaan 47, 2712 GB',
    lat: 52.052509,
    lng: 4.495426,
    type: 'store',
  },
  {
    id: 'nl-night-markt',
    name: 'Night Markt',
    country: 'Netherlands',
    city: 'Leiden',
    address: 'steenstraat 7, 2312 BS',
    lat: 52.16325,
    lng: 4.484383,
    type: 'store',
  },
  {
    id: 'nl-avondwinkel-pitstop',
    name: 'Avondwinkel Pitstop',
    country: 'Netherlands',
    city: '\'s-Gravenhage',
    address: 'Laan van meerdervoort 492, 2563 BJ',
    lat: 52.075619,
    lng: 4.269096,
    type: 'store',
  },
  {
    id: 'nl-kamaj',
    name: 'Kamaj',
    country: 'Netherlands',
    city: 'Duivendrecht',
    address: 'Ellemanstraat 28, 10099 BZ',
    lat: 52.330857,
    lng: 4.938743,
    type: 'store',
  },
  {
    id: 'nl-malhi-import-export',
    name: 'Malhi import Export',
    country: 'Netherlands',
    city: 'Amsterdam',
    address: 'Centrale Groothandelsmarkt 111, 1051 LJ',
    lat: 52.376861,
    lng: 4.86888,
    type: 'store',
  },
  {
    id: 'nl-supermarkt-nil',
    name: 'Supermarkt Nil',
    country: 'Netherlands',
    city: 'Rotterdam',
    address: 'Jacob van Campenplein 192, 3067 LE',
    lat: 51.943433,
    lng: 4.538206,
    type: 'store',
  },
  {
    id: 'nl-amar-import-en-export',
    name: 'Amar Import en Export',
    country: 'Netherlands',
    city: '\'s-Gravenhage',
    address: 'Vlist 45, 2491 CC',
    lat: 52.066792,
    lng: 4.389958,
    type: 'store',
  },
  {
    id: 'nl-markisto',
    name: 'Markisto',
    country: 'Netherlands',
    city: '\'s-Gravenhage',
    address: 'Traag 1, 2491 CR',
    lat: 52.0661,
    lng: 4.387146,
    type: 'store',
  },
  {
    id: 'nl-supermarkt-tropicana-bv',
    name: 'Supermarkt Tropicana BV',
    country: 'Netherlands',
    city: 'Rotterdam',
    address: 'Boezemstraat 28, 3034 KC',
    lat: 51.933863,
    lng: 4.498484,
    type: 'store',
  },
  {
    id: 'nl-rcnb-global',
    name: 'RCNB Global',
    country: 'Netherlands',
    city: 'Capelle aan den IJssel',
    address: 'Boomkensdiep 131, 2904 EH',
    lat: 51.936137,
    lng: 4.602999,
    type: 'store',
  },
  {
    id: 'nl-avantage-supermarkt-wielwijk',
    name: 'Avantage Supermarkt Wielwijk',
    country: 'Netherlands',
    city: 'Dordrecht',
    address: 'Admiraalsplein 68-70, 3317 BC',
    lat: 51.791516,
    lng: 4.653778,
    type: 'store',
  },
  {
    id: 'nl-vega-delight-bv',
    name: 'Vega Delight BV',
    country: 'Netherlands',
    city: 'Rotterdam',
    address: 'Postbus 53017, 3008 HA',
    lat: 51.9225,
    lng: 4.47917,
    type: 'store',
    approx: true, // alleen postbus bekend — pin bij benadering
  },
  {
    id: 'nl-broodje-lobi-oud-beijerland',
    name: 'Broodje Lobi Oud-Beijerland',
    country: 'Netherlands',
    city: 'Oud-Beijerland',
    address: 'Oost-voorstraat 63, 3262 JG',
    lat: 51.824031,
    lng: 4.412542,
    type: 'store',
  },
  {
    id: 'nl-highway-supermarkt',
    name: 'Highway Supermarkt',
    country: 'Netherlands',
    city: 'Rotterdam',
    address: 'Dordtselaan 167, 3081 BN',
    lat: 51.890692,
    lng: 4.493655,
    type: 'store',
  },
  {
    id: 'nl-happy-surinees',
    name: 'happy surinees',
    country: 'Netherlands',
    city: 'Rotterdam',
    address: 'Kleine Beer 3, 3067 ZW',
    lat: 51.949428,
    lng: 4.554446,
    type: 'store',
  },
  {
    id: 'nl-tabak-gemak-napoleon',
    name: 'Tabak & Gemak Napoleon',
    country: 'Netherlands',
    city: 'Vlaardingen',
    address: 'Schiedamseweg 55-8, 3134 BB',
    lat: 51.90944,
    lng: 4.347776,
    type: 'store',
  },
  {
    id: 'nl-bij-buuf',
    name: 'Bij Buuf',
    country: 'Netherlands',
    city: 'Schiedam',
    address: 'Hoogstraat 182a, 3111 HP',
    lat: 51.917667,
    lng: 4.397572,
    type: 'store',
  },
  {
    id: 'nl-i-tenia',
    name: 'I-Tenia',
    country: 'Netherlands',
    city: 'Rotterdam',
    address: 'Jacques Dutilhweg 188, 3065 KA',
    lat: 51.929899,
    lng: 4.560087,
    type: 'store',
  },
  {
    id: 'nl-two22-studio-bv',
    name: 'Two22 Studio BV',
    country: 'Netherlands',
    city: 'Rotterdam',
    address: 'Goudsewagenstraat 16, 3011 RK',
    lat: 51.923444,
    lng: 4.493659,
    type: 'store',
  },
  {
    id: 'nl-gall-en-gall-prinseland',
    name: 'Gall en Gall Prinseland',
    country: 'Netherlands',
    city: 'Rotterdam',
    address: 'Mia van Ijperenplein 85',
    lat: 51.92858,
    lng: 4.546417,
    type: 'store',
  },
  {
    id: 'nl-sunda-food-group',
    name: 'Sunda Food Group',
    country: 'Netherlands',
    city: '\'s-Gravenhage',
    address: 'Dinkel 88, 2491 CH',
    lat: 52.065592,
    lng: 4.388768,
    type: 'store',
  },
  {
    id: 'nl-noepa-impex',
    name: 'Noepa Impex',
    country: 'Netherlands',
    city: '\'s-Gravenhage',
    address: 'Dinkel 56, 2491 CH',
    lat: 52.06613,
    lng: 4.387952,
    type: 'store',
  },
  {
    id: 'nl-supermarkt-dya',
    name: 'Supermarkt Dya',
    country: 'Netherlands',
    city: 'Dordrecht',
    address: 'Vogelplein 43, 3312 GS',
    lat: 51.809987,
    lng: 4.683831,
    type: 'store',
  },
  {
    id: 'nl-toko-alexander',
    name: 'Toko Alexander',
    country: 'Netherlands',
    city: 'Rotterdam',
    address: 'Jacob van Campenplein 192, 3067 LE',
    lat: 51.943433,
    lng: 4.538206,
    type: 'store',
  },
  {
    id: 'nl-gall-gall',
    name: 'Gall & Gall',
    country: 'Netherlands',
    city: 'Rotterdam',
    address: 'Spinozaweg 197, 3076 EL',
    lat: 51.877397,
    lng: 4.5206,
    type: 'store',
  },
  {
    id: 'nl-pilates-studio-east',
    name: 'Pilates Studio East',
    country: 'Netherlands',
    city: 'Capelle aan den IJssel',
    address: 'Lylantse Plein 2, 2908 LH',
    lat: 51.954785,
    lng: 4.568388,
    type: 'store',
  },
  {
    id: 'nl-plus-kevin-van-dam',
    name: 'Plus Kevin van Dam',
    country: 'Netherlands',
    city: 'Rotterdam',
    address: 'Van Beethovensingel 4, 3055 JJ',
    lat: 51.960092,
    lng: 4.503767,
    type: 'store',
  },
  {
    id: 'nl-yasam-supermarkt',
    name: 'Yasam Supermarkt',
    country: 'Netherlands',
    city: 'Rotterdam',
    address: 'Wolphaertsbocht 52, 3082 AC',
    lat: 51.893736,
    lng: 4.467959,
    type: 'store',
  },
  {
    id: 'nl-royaal-slijterij',
    name: 'Royaal Slijterij',
    country: 'Netherlands',
    city: '\'s-Gravenhage',
    address: 'Weimarstraat 172, 2562 HD',
    lat: 52.0754,
    lng: 4.280527,
    type: 'store',
  },
  {
    id: 'nl-plus-hoogendoorn',
    name: 'Plus Hoogendoorn',
    country: 'Netherlands',
    city: 'Poortugaal',
    address: 'Waalstraat 2a, 3171 AH',
    lat: 51.857059,
    lng: 4.390777,
    type: 'store',
  },
  {
    id: 'nl-basis-e-markt',
    name: 'Basis e Markt',
    country: 'Netherlands',
    city: 'Rotterdam',
    address: 'Groene Dilledijk 172, 3074 AA',
    lat: 51.893135,
    lng: 4.509567,
    type: 'store',
  },
  {
    id: 'nl-coffee-star-coffee-bikes',
    name: 'Coffee-Star Coffee & Bikes',
    country: 'Netherlands',
    city: '\'s-Gravenhage',
    address: 'Laan van meerdervoort 783, 2564 AG',
    lat: 52.07066,
    lng: 4.254291,
    type: 'store',
  },
  {
    id: 'nl-number-ten',
    name: 'Number Ten',
    country: 'Netherlands',
    city: 'Rotterdam',
    address: 'Hoogstraat 47a, 3011 PG',
    lat: 51.9229,
    lng: 4.493402,
    type: 'store',
  },
  {
    id: 'nl-royaal-catering-service',
    name: 'Royaal Catering Service',
    country: 'Netherlands',
    city: '\'s-Gravenhage',
    address: 'Koolwitjelaan 116, 2496 ZM',
    lat: 52.054103,
    lng: 4.380127,
    type: 'store',
  },
  {
    id: 'nl-royaal-horeca-bv',
    name: 'Royaal Horeca BV',
    country: 'Netherlands',
    city: 'Delft',
    address: 'Hazelwormstraat 1, 2623 CH',
    lat: 51.985594,
    lng: 4.360366,
    type: 'store',
  },
  {
    id: 'nl-toko-sodiro',
    name: 'Toko Sodiro',
    country: 'Netherlands',
    city: 'Rotterdam',
    address: 'Binnenhof 60, 3068 JW',
    lat: 51.959902,
    lng: 4.534528,
    type: 'store',
  },
  {
    id: 'nl-plus-meeuw',
    name: 'Plus Meeuw',
    country: 'Netherlands',
    city: 'Spijkenisse',
    address: 'Winterakker 21, 3206 TG',
    lat: 51.833331,
    lng: 4.32027,
    type: 'store',
  },
  {
    id: 'nl-avondwinkel-charlois',
    name: 'Avondwinkel Charlois',
    country: 'Netherlands',
    city: 'Rotterdam',
    address: 'Dorpsweg 43A, 3082 LB',
    lat: 51.890348,
    lng: 4.472459,
    type: 'store',
  },
  {
    id: 'nl-spice-street-bv',
    name: 'Spice Street BV',
    country: 'Netherlands',
    city: 'Rotterdam',
    address: 'Noordplein 167, 3035 ED',
    lat: 51.93041,
    lng: 4.483562,
    type: 'store',
  },
  {
    id: 'nl-plus-van-holten-nieuw-lekker',
    name: 'Plus van Holten Nieuw-Lekkerland',
    country: 'Netherlands',
    city: 'Nieuw-Lekkerland',
    address: 'Kleyburgplein 9, 2957 AT',
    lat: 51.889454,
    lng: 4.687578,
    type: 'store',
  },
  {
    id: 'nl-sanvir',
    name: 'Sanvir',
    country: 'Netherlands',
    city: 'Amsterdam',
    address: 'Centrale Groothandelsmarkt 141, 1051 LJ',
    lat: 52.380145,
    lng: 4.867817,
    type: 'store',
  },
  {
    id: 'nl-avondwinkel-uno',
    name: 'Avondwinkel Uno',
    country: 'Netherlands',
    city: 'Amsterdam',
    address: 'Pieter Calendlaan 17, 1065 KH',
    lat: 52.356129,
    lng: 4.830056,
    type: 'store',
  },
  {
    id: 'nl-chindothai-bv',
    name: 'Chindothai BV',
    country: 'Netherlands',
    city: 'Hellevoetsluis',
    address: 'Struytse Hoeck 320, 3223 DE',
    lat: 51.832703,
    lng: 4.145803,
    type: 'store',
  },
  {
    id: 'nl-pud-the-stable',
    name: 'Pud The Stable',
    country: 'Netherlands',
    city: 'Rotterdam',
    address: 'Paul Krugerstraat 133B, 3072 GH',
    lat: 51.899895,
    lng: 4.498014,
    type: 'store',
  },
  {
    id: 'nl-kizomba-lounge',
    name: 'Kizomba Lounge',
    country: 'Netherlands',
    city: 'Rotterdam',
    address: 'Willem de Zwijgerstraat 23B, 3043 VB',
    lat: 51.941846,
    lng: 4.423798,
    type: 'store',
  },
  {
    id: 'nl-plus-s-gravenland-capelle-bv',
    name: 'Plus s-Gravenland Capelle Bv',
    country: 'Netherlands',
    city: 'Capelle aan den IJssel',
    address: 'Puccinipassage 12, 2901 GK',
    lat: 51.917768,
    lng: 4.566043,
    type: 'store',
  },
  {
    id: 'nl-cafe-bradazz',
    name: 'Cafe Bradazz',
    country: 'Netherlands',
    city: 'Rotterdam',
    address: 'Beijerlandselaan 82, 3074 EM',
    lat: 51.897029,
    lng: 4.511162,
    type: 'store',
  },
  {
    id: 'nl-sue',
    name: 'SUE',
    country: 'Netherlands',
    city: 'Rotterdam',
    address: 'Karel Doormanstraat 372, 3012 GR',
    lat: 51.918633,
    lng: 4.47631,
    type: 'store',
  },
  {
    id: 'nl-avondsupermarkt-de-tulp',
    name: 'Avondsupermarkt de Tulp',
    country: 'Netherlands',
    city: '\'s-Gravenhage',
    address: 'Rijswijkseweg 610, 2516 HW',
    lat: 52.060928,
    lng: 4.334186,
    type: 'store',
  },
  {
    id: 'nl-xl-horecagroothandel-bv',
    name: 'XL Horecagroothandel BV',
    country: 'Netherlands',
    city: 'Wateringen',
    address: 'Turfschipper 116, 2292 JB',
    lat: 52.01575,
    lng: 4.29005,
    type: 'store',
  },
  {
    id: 'nl-plus-halsteren-bv',
    name: 'Plus Halsteren BV',
    country: 'Netherlands',
    city: 'Halsteren',
    address: 'Dorpsstraat 75, 4661 HN',
    lat: 51.523695,
    lng: 4.271444,
    type: 'store',
  },
  {
    id: 'nl-plus-blijdorp',
    name: 'Plus Blijdorp',
    country: 'Netherlands',
    city: 'Rotterdam',
    address: 'Stadhoudersplein 135, 3038 EA',
    lat: 51.9319,
    lng: 4.463396,
    type: 'store',
  },
  {
    id: 'nl-avondwinkel-vredebest',
    name: 'Avondwinkel Vredebest',
    country: 'Netherlands',
    city: 'Gouda',
    address: 'Vredebest 10, 2801 AS',
    lat: 52.016031,
    lng: 4.708959,
    type: 'store',
  },
  {
    id: 'nl-casa-django',
    name: 'Casa Django',
    country: 'Netherlands',
    city: 'Dordrecht',
    address: 'Spuiweg 62, 3311 GV',
    lat: 51.810718,
    lng: 4.66329,
    type: 'store',
  },
  {
    id: 'nl-plus-viergever-maasdijk',
    name: 'Plus Viergever Maasdijk',
    country: 'Netherlands',
    city: 'Maasdijk',
    address: 'Oranjeplein 1, 2676 XP',
    lat: 51.959909,
    lng: 4.214637,
    type: 'store',
  },
  {
    id: 'nl-plus-van-holten-alblasserdam',
    name: 'Plus van Holten Alblasserdam',
    country: 'Netherlands',
    city: 'Alblasserdam',
    address: 'Sportlaan 1, 2951 HL',
    lat: 51.867804,
    lng: 4.664879,
    type: 'store',
  },
  {
    id: 'nl-plus-tom-vlig-schiebroek',
    name: 'Plus Tom Vlig Schiebroek',
    country: 'Netherlands',
    city: 'Rotterdam',
    address: 'Ganzerikplein 329, 3053 EA',
    lat: 51.959008,
    lng: 4.472135,
    type: 'store',
  },
  {
    id: 'nl-plus-te-kulve-capelle',
    name: 'Plus te Kulve Capelle aan den IJssel',
    country: 'Netherlands',
    city: 'Capelle aan den IJssel',
    address: 'Slotplein 16, 2902 HP',
    lat: 51.924101,
    lng: 4.583750,
    type: 'store',
  },
  {
    id: 'nl-plus-te-kulve-nieuwerkerk',
    name: 'Plus te Kulve Nieuwerkerk aan den IJssel',
    country: 'Netherlands',
    city: 'Nieuwerkerk aan den IJssel',
    address: 'Dorrestein 21, 2912 BC',
    lat: 51.965949,
    lng: 4.607103,
    type: 'store',
  },
  {
    id: 'nl-plus-koelhuis-bergschenhoek',
    name: 'Plus Koelhuis Bergschenhoek',
    country: 'Netherlands',
    city: 'Bergschenhoek',
    address: 'de Vlashoeck 24 30, 2661 LM',
    lat: 51.988563,
    lng: 4.501392,
    type: 'store',
  },
  {
    id: 'nl-plus-richard-de-zoete-overschie',
    name: 'Plus Richard de Zoete Overschie',
    country: 'Netherlands',
    city: 'Rotterdam',
    address: 'Burg. Baumannlaan 187, 3042 AD',
    lat: 51.934695,
    lng: 4.428481,
    type: 'store',
  },
  {
    id: 'nl-plus-verhoeven-ommoord',
    name: 'Plus Verhoeven Ommoord',
    country: 'Netherlands',
    city: 'Rotterdam',
    address: 'Binnenhof 2, 3069 KV',
    lat: 51.960645,
    lng: 4.535093,
    type: 'store',
  },
  {
    id: 'nl-plus-martin-panis-delft',
    name: 'Plus Martin Panis Delft',
    country: 'Netherlands',
    city: 'Delft',
    address: 'Van Foreestweg 4a, 2614 CJ',
    lat: 52.013364,
    lng: 4.337267,
    type: 'store',
  },
  {
    id: 'nl-boons-markt-barendrecht',
    name: "Boon's Markt Barendrecht",
    country: 'Netherlands',
    city: 'Barendrecht',
    address: 'Marijkesingel 18, 2991 BK',
    lat: 51.850835,
    lng: 4.548933,
    type: 'store',
  },
  {
    id: 'nl-boons-markt-rhoon',
    name: "Boon's Markt Rhoon",
    country: 'Netherlands',
    city: 'Rhoon',
    address: 'Tsjaikovskistraat 3, 3161 WH',
    lat: 51.856222,
    lng: 4.420851,
    type: 'store',
  },
]

export const typeColors = {
  hq: '#51b83e',
  store: '#7fce6c',
  distributor: '#f2c14e',
}

export const typeLabels = {
  hq: 'Hoofdkantoor',
  store: 'Verkooppunt',
  distributor: 'Distributeur',
}
